### ISSUE TITLE
Parent Issue - Improvements to OpenEBS Project

### ISSUE THREAD

**Issue by avishnu** [openebs/openebs#3701]
OpenEBS is the most popular and widely used CNCF Kubernetes storage platform project. More than 700,000 people rely on our project for fast + reliable Kubernetes native storage. OpenEBS has been a CNCF sandbox project since 2019, open source and completely free. DataCore Software sponsors the project and donates significant community resources to the daily engineering of the project via a world-class storage engineering team of 20+ engineers, working together with hundreds of community contributors from across the world.

The CNCF Technical Oversight Committee (TOC) advised the project team to make changes to the project: improve community experience for repo + project structure, ensure documentation is current, improve project governance (see issue [#1051](https://github.com/cncf/toc/issues/1051)). In Feb 2024, CNCF TOC changed the project status to “Archive” and invited our team to implement these changes, then re-apply for promotion to Sandbox.

To TOC and our hundreds-of-thousands of users: thank you for your support. Yes we intend to make these improvements and re-apply to CNCF Sandbox after they are completed. During this process, we will update our community with what we intend to do, and progress against plan.

This is the parent issue for tracking our improvement project. We will post information soon on changes that unify product functionality and project roadmaps.

Finally, if you’re using OpenEBS, and if you’ve had a positive experience, and wish to show your support, please leave a comment below and add yourself to our [ADOPTERS.md](https://github.com/openebs/openebs/blob/main/ADOPTERS.md) file.

- [x] Deprecation announcement on GitHub (#3709)
- [x] Deprecation announcement on Slack
- [x] Update MAINTAINERS (#3708)
- [x] Update GOVERNANCE
- [x] Update ROADMAP
- [x] Provide migration guides from legacy to active (https://openebs.io/docs/user-guides/data-migration/migration-overview)
- [ ] Update README for all legacy projects
- [ ] Restructure OpenEBS issues
- [x] Restructure documentation
- [x] Move and publish OpenEBS Helm chart from https://github.com/openebs/openebs
- [x] Release OpenEBS v4.0.0
- [x] Move legacy repositories to https://github.com/openebs-archive (https://github.com/openebs/community/issues/8)

**Comment by orville-wright** [comment]
Thanks for the update @avishnu - :heart: :rocket: OpenEBS

**Comment by edrob999** [comment]
An update for everyone: In the Community repository, there are draft documents for Vision, Governance, Contributing. The idea is: these will apply as an umbrella across all projects/repositories in the OpenEBS organization. The stuff we're working on is being tracked in the Community repo Issues

**Comment by edrob999** [comment]
Happy Monday, as announced in #3709, today project team moved 44 repos from the OpenEBS org to OpenEBS-archive org. The archive org is intended to provide as-is snapshots of legacy artifacts, and not for active development. We expect to add more to the archive over time
The 44 repositories are:
openebs/charts
openebs/libiscsi
openebs-archive/wingetopt
openebs/spl
openebs/blkid-sys
openebs/vhost-user
openebs/sys-mount
openebs/fbench
openebs/opensea-operations
openebs/opensea-common
openebs/opensea-transport
openebs/dbench
openebs/proc-mounts
openebs/spdk-sys 
openebs/blkid
openebs/partition-identity
openebs/elves
openebs/longhorn
openebs/sparse-tools
openebs/gotgt
openebs/jiva-csi
openebs/external-storage
openebs/openebs-k8s-provisioner
openebs/e2e-tests 
openebs/helm-operator
openebs/sts-pv-pvc-handler
openebs/openebs-docs
openebs/monitor-pv
openebs/openSeaChest
openebs/mayastor-charts
openebs/device-localpv
openebs/node-disk-manager
openebs/rust-git-version
openebs/go-ogle-analytics
openebs/api 
openebs/dynamic-nfs-provisioner
openebs/libcstor
openebs/jiva
openebs/m-exporter
openebs/cstor-csi 
openebs/upgrade
openebs/jiva-operator
openebs/cstor-operators
openebs/istgt

**Comment by edrob999** [comment]
The last release that included the now-archived-repos was OpenEBS Standard 3.10. We updated the helm charts, so this installation is working OK. See: https://openebs.io/docs/3.10.x/user-guides/installation

From OpenEBS 4.0 onwards, these legacy engines and projects will not be not available in the OpenEBS installation.

**Comment by edrob999** [comment]
Update: We moved openebs/charts from openebs-archive to openebs org, because of issues with the helm charts for the archived projects

**Comment by Ornias1993** [comment]
As I've stated in the CNCF archival issues, I do not think OpenEBS is ready for readmittance any time soon.

An organisation making amateuristic mistakes with Helm Charts, causing breakage along their complete userbase, has so much to learn, or needs so much oversight, that it has no place within the CNCF landscape.

That is:
The accountability and consequences for people making said mistakes, is the primary concern.
The way MayaData, maintaining OpenEBS, is handling that, does not seem to meet statisfactory standards for production-ready CNCF software.

**Comment by edrob999** [comment]
@Ornias1993 you've posted this on multiple forums. Everyone sees your problem.

In the OpenEBS project, we try to be respectful of differing opinions, viewpoints, and experiences.  Its OK to criticize the project, but not derogatory comments about the contributors. Again I'm happy to talk it thru.
Ed

**Comment by Ornias1993** [comment]
> @Ornias1993 you've posted this on multiple forums. Everyone sees your problem.

I've not "posted it on multiple forums", just here and with the CNCF where it is actually an issue.

> Its OK to criticize the project, but not derogatory comments about the contributors.

Lets turn a valid argument about a specific employee of Mayadata making huge mistakes potentially leading to production downtime *multiple times* into a "you're mean" issue. Just because the truth is nasty and you don't want to hear it, does not make it true.

>  Again I'm happy to talk it thru.

I'll leave it at being a CNCF issue, as I don't see any productive resolution and taking of accountability from MayaData.
Not previously and not now.

I've no interest in a "de-escalation talk", I want to see actual steps to ensure these huge fuckups don't happen in the future and taking of responsibility. Which I'm not seeing.

If you would actually be interested in that, you would already have publically listed all the steps, procedures and consequences put-in-place to prevent this level of mistakes in the future.

**Comment by edrob999** [comment]
Update on governance for the OpenEBS umbrella project:
The maintainers met today (started meeting weekly on Wednesday's 7am Pacific). 
[A record of this meeting is here](https://github.com/openebs/community/discussions/50#discussioncomment-9680016)

The next community meeting will be Thursday 27 June, then monthly on last-thursday-of-the-month.

The material improvements to the OpenEBS project are complete, and the project will start adhering to its governance procedures

**Comment by edrob999** [comment]
In the last few months we've made the following improvements to the project:
* Moved about two-thirds of the repos to an [archive organization](https://github.com/openebs-archive)
* Created and populated a community repo
* Rewritten the governance, contributing, vision, readme project documentation for the umbrella project, and done each with thought and care
* Ensured all the individual sub-project project documentation either point to or complement the umbrella files
* Released OpenEBS Standard 4.0
* Updated all the documentation on [openebs.io](https://openebs.io)

There is always more work to do! hopefully everyone appreciates the work so far.

**Comment by edrob999** [comment]
Continuing the improvements: Maintainers voted to archive [data populator](https://github.com/openebs/data-populator), because functionality is provided by other community projects.  Repo will be archived after three weeks (on or after 10 July)

**Comment by edrob999** [comment]
OpenEBS was accepted into Sandbox last week see: https://github.com/cncf/sandbox/issues/104

@avishnu I recommend we can this issue now

**Comment by avishnu** [comment]
Yes, OpenEBS has been voted in for Sandbox!! Any further improvements will be taken up via separate issues. Closing this now. Thanks to all.
